
platform :ios, '9.0'
use_frameworks!
inhibit_all_warnings!

def shared
pod 'TPKeyboardAvoiding', '~> 1.3.1'
end

target 'MyGro' do
shared
pod 'Alamofire', '~> 4.4.0'
pod 'AlamofireImage', '~> 3.2.0'
pod 'SnapKit', '~> 3.2.0'
pod 'Locksmith', '~> 3.0.0'
pod 'SwiftyAttributes', '~> 3.1.0'
end

target 'MyGroTests' do
shared
end
